# Project: 项目2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 1.o
LINKOBJ  = 1.o
LIBS     = -L"D:/Game/Demo/Dev-Cpp/MinGW64/lib" -L"D:/Game/Demo/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Game/Demo/Dev-Cpp/MinGW64/include" -I"D:/Game/Demo/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Game/Demo/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Game/Demo/Dev-Cpp/MinGW64/include" -I"D:/Game/Demo/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Game/Demo/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Game/Demo/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

1.o: 1.cpp
	$(CPP) -c 1.cpp -o 1.o $(CXXFLAGS)
